---
title: "Simple In-memory Decoding of PNG Data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Simple In-memory Decoding of PNG Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(spng)
library(pixelweaver)
```


# Introduction

This vignette shows how to 

* Read a PNG as raw bytes
* Extract height and width from the PNG data
* Decode the PNG file into pixel data
* Reshape the packed color data into something R understands
    * manually
    * using [pixelweaver](https://github.com/coolbutuseless/pixelweaver)


```{r}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Read in raw bytes representing a PNG image
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
png_file <- system.file("img", "Rlogo.png", package="png")
png_data <- readBin(png_file, 'raw', n = file.size(png_file))
png_info <- spng::png_info(png_data)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Decode the PNG data to image data in-memory. Returned data is 
# packed color in ABGR32 format.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
img_data <- spng::depng(png_data, fmt = spng_format$SPNG_FMT_RGBA8)

head(img_data, 200)
```



## Manually onvert packed color data to array data

```{r}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Construct an array by plucking the relevant bytes.
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
N <- length(img_data)

arr <- array(
  c(
    img_data[seq(1, N, 4)], # R
    img_data[seq(2, N, 4)], # G
    img_data[seq(3, N, 4)], # B
    img_data[seq(4, N, 4)]  # A
  ),
  dim = c(png_info$width, png_info$height, 4)
)

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# PNG bytes are in row-major order. R is in column major order
# so need to transpose to view correctly
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
arr <- aperm(arr, c(2, 1, 3))
plot(as.raster(arr))
```


## Convert packed color data to array data using `{pixelweaver}`

```{r}
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Convert the packed color directly into an R array with 4 channels (RGBA)
# This will also transpose the result into column-major representation
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
arr4 <- pixelweaver::packed_to_planar(
  packed_data = img_data, 
  format      = packed_fmt$ABGR32, # Packed color format
  nchannel    = 4,                 # Output array color depth
  width       = png_info$width, 
  height      = png_info$height
)


dim(arr4)
plot(as.raster(arr4))
```

